#!/usr/bin/env node
import { Command, Option } from 'commander';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import pc from 'picocolors';
import type { GeneratedChangelog, GitCommit, Language, Provider } from './types.js';
import { resolveRange, repoName, hasUncommittedChanges } from './git.js';
import { commitsToPrompt, detectLanguage, isBreaking } from './commits.js';
import { bumpVersion, suggestBump, versionFromTag } from './semver.js';
import { generateFallback } from './fallback.js';
import { generateWithLlm, detectProvider, type LlmConfig } from './llm.js';
import { renderJson, renderMarkdown, renderTerminal } from './render.js';

interface CliOptions {
  repo?: string;
  from?: string;
  to?: string;
  provider?: Provider;
  model?: string;
  apiKey?: string;
  baseUrl?: string;
  lang?: string;
  format?: string;
  write?: boolean;
  noLlm?: boolean;
  setVersion?: string;
}

function today(): string {
  const d = new Date();
  const p = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`;
}

/** Insert a new version section at the top of an existing CHANGELOG.md. */
function prependToChangelog(path: string, section: string): void {
  const header = "# Changelog\n\n";
  const existing = existsSync(path) ? readFileSync(path, 'utf-8') : '';
  let rest = existing;
  if (rest.startsWith(header)) rest = rest.slice(header.length);
  // Remove the "## [Unreleased]" block if present so it does not shadow the new section.
  rest = rest.replace(/## \[Unreleased\][\s\S]*?(?=## |\Z)/i, '');
  const next = header + section.trimEnd() + '\n\n' + rest.trimStart();
  writeFileSync(path, next, 'utf-8');
}

function resolveLanguage(lang: string | undefined, commits: GitCommit[]): Language {
  return lang === 'zh' || lang === 'en' ? lang : detectLanguage(commits);
}

async function main() {
  const program = new Command();
  program
    .name('ai-changelog')
    .description('AI-powered changelog & release notes generator from git history.')
    .version('1.0.0')
    .option('--repo <path>', 'path to the git repository (default: current directory)')
    .option('--from <ref>', 'base git ref (default: latest tag; falls back to first commit)')
    .option('--to <ref>', 'head git ref (default: HEAD)')
    .addOption(new Option('--provider <name>', 'LLM provider').choices(['openai', 'deepseek', 'anthropic', 'ollama', 'auto']).default('auto'))
    .option('--model <name>', 'LLM model name')
    .option('--api-key <key>', 'API key (or use the <PROVIDER>_API_KEY env var)')
    .option('--base-url <url>', 'custom OpenAI-compatible base URL')
    .addOption(new Option('--lang <lang>', 'output language (auto detects from commits)').choices(['auto', 'zh', 'en']).default('auto'))
    .addOption(new Option('--format <format>', 'output format').choices(['terminal', 'md', 'json']).default('terminal'))
    .option('--write', 'prepend the new section to CHANGELOG.md in the repo')
    .option('--no-llm', 'force the built-in rule engine, skip LLM calls')
    .option('--set-version <version>', 'explicit version for the changelog title (e.g. 1.2.0)')
    .parse(process.argv);
  const opts = program.opts<CliOptions>();

  const repo = opts.repo ? resolve(opts.repo) : process.cwd();
  const { commits, fromTag, range } = resolveRange(repo, opts.from, opts.to);

  if (commits.length === 0) {
    console.error(pc.yellow(`No commits found in range "${range}".`));
    process.exit(1);
  }

  if (hasUncommittedChanges(repo)) {
    console.error(pc.yellow('Warning: the working tree has uncommitted changes; generated notes may miss them.'));
  }

  // Resolve provider.
  let provider = opts.provider ?? 'auto';
  if (provider === 'auto') provider = detectProvider();
  const useLlm = !opts.noLlm;

  // Resolve the version to title the section.
  const bump = suggestBump(commits);
  const fromTagVersion = fromTag ? versionFromTag(fromTag) : undefined;
  const nextVersion = opts.setVersion ?? bumpVersion(fromTagVersion, bump);
  const breakingCount = commits.filter(isBreaking).length;

  let generated: GeneratedChangelog;
  if (useLlm && provider !== 'auto') {
    const cfg: LlmConfig = {
      provider,
      model: opts.model,
      apiKey: opts.apiKey,
      baseUrl: opts.baseUrl,
      language: resolveLanguage(opts.lang, commits),
      repoName: repoName(repo),
      version: nextVersion,
      commitList: commitsToPrompt(commits),
      commitCount: commits.length,
    };
    const result = await generateWithLlm(cfg);
    if (result.ok && result.markdown) {
      generated = {
        title: `## [${nextVersion}] - ${today()}`,
        bump,
        nextVersion,
        groups: [{ name: 'Generated by LLM', entries: [result.markdown] }],
        markdown: `## [${nextVersion}] - ${today()}\n\n${result.markdown}\n`,
        usedLlm: true,
      };
    } else {
      console.error(pc.dim(`LLM unavailable (${result.error || "unknown error"}) — falling back to the rule engine.`));
      generated = generateFallback(commits, { language: resolveLanguage(opts.lang, commits), nextVersion, date: today() });
    }
  } else {
    generated = generateFallback(commits, { language: resolveLanguage(opts.lang, commits), nextVersion, date: today() });
  }

  const format = opts.format ?? 'terminal';
  let output = '';
  if (format === 'json') output = renderJson(generated);
  else if (format === 'md') output = renderMarkdown(generated);
  else output = renderTerminal(generated);
  process.stdout.write(output + '\n');

  if (breakingCount > 0) {
    console.error(pc.bold(pc.red(`⚠  ${breakingCount} breaking change(s) detected — consider a major version bump.`)));
  }

  if (opts.write) {
    const changelogPath = resolve(repo, 'CHANGELOG.md');
    prependToChangelog(changelogPath, generated.markdown);
    console.error(pc.green(`✓ Wrote ${changelogPath}`));
  }
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : String(err));
  process.exit(1);
});
